image: ubuntu:16.04

stages:
  - builder
  - compile
  - kpi
  - publish

xenial:builder:
  stage: builder
  script:
    - echo builder:xenial

# ---------------------------------------------------------------------------- #

xenial:compile:release:
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  image: xtdcpp/builder/xenial
  dependencies:
  - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:compile:debug:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:kpi:doc:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} doc
    - make -C ${CI_BUILDDIR} doc-coverage -j

xenial:kpi:unittest:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} check -j
    - make -C ${CI_BUILDDIR} memcheck -j

xenial:kpi:coverage:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cov -j

xenial:kpi:cloc:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cloc -j

xenial:kpi:cppcheck:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cppcheck -j

xenial:publish:
  image: xtdcpp/builder/xenial
  stage: publish
  dependencies:
    - xenial:kpi:cppcheck
    - xenial:kpi:cloc
    - xenial:kpi:coverage
    - xenial:kpi:unittest
    - xenial:kpi:doc
  script:
    - echo xenial:publish

# ---------------------------------------------------------------------------- #

trusty:compile:release:
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  image: xtdcpp/builder/trusty
  dependencies:
  - trusty:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

trusty:compile:debug:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

trusty:kpi:doc:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  dependencies:
    - trusty:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} doc
    - make -C ${CI_BUILDDIR} doc-coverage -j

trusty:kpi:unittest:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  dependencies:
    - trusty:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} check -j
    - make -C ${CI_BUILDDIR} memcheck -j

trusty:kpi:coverage:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cov -j

trusty:kpi:cloc:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cloc -j

trusty:kpi:cppcheck:
  image: xtdcpp/builder/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cppcheck -j

trusty:publish:
  image: xtdcpp/builder/trusty
  stage: publish
  dependencies:
    - trusty:kpi:cppcheck
    - trusty:kpi:cloc
    - trusty:kpi:coverage
    - trusty:kpi:unittest
    - trusty:kpi:doc
  script:
    - echo trusty:publish

# # ---------------------------------------------------------------------------- #

# precise:compile:release:
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: release
#   image: xtdcpp/builder/precise
#   dependencies:
#   - precise:builder
#   stage: compile
#   script:
#     - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
#     - cd ${CI_PROJECT_DIR} && git submodule init
#     - cd ${CI_PROJECT_DIR} && git submodule update
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
#     - make -C ${CI_BUILDDIR} all -j

# precise:compile:debug:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: debug
#   dependencies:
#     - precise:builder
#   stage: compile
#   script:
#     - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
#     - cd ${CI_PROJECT_DIR} && git submodule init
#     - cd ${CI_PROJECT_DIR} && git submodule update
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
#     - make -C ${CI_BUILDDIR} all -j

# precise:kpi:doc:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: release
#   dependencies:
#     - precise:compile:release
#   stage: kpi
#   script:
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - make -C ${CI_BUILDDIR} doc
#     - make -C ${CI_BUILDDIR} doc-coverage -j

# precise:kpi:unittest:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: release
#   dependencies:
#     - precise:compile:release
#   stage: kpi
#   script:
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - make -C ${CI_BUILDDIR} check -j
#     - make -C ${CI_BUILDDIR} memcheck -j

# precise:kpi:coverage:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: debug
#   dependencies:
#     - precise:compile:debug
#   stage: kpi
#   script:
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - make -C ${CI_BUILDDIR} cov -j

# precise:kpi:cloc:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: debug
#   dependencies:
#     - precise:compile:debug
#   stage: kpi
#   script:
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - make -C ${CI_BUILDDIR} cloc -j

# precise:kpi:cppcheck:
#   image: xtdcpp/builder/precise
#   variables:
#     CI_LSB_RELEASE: precise
#     CI_BUILD_TYPE: debug
#   dependencies:
#     - precise:compile:debug
#   stage: kpi
#   script:
#     - . ${CI_PROJECT_DIR}/gitlab-ci/env
#     - make -C ${CI_BUILDDIR} cppcheck -j

# precise:publish:
#   image: xtdcpp/builder/precise
#   stage: publish
#   dependencies:
#     - precise:kpi:cppcheck
#     - precise:kpi:cloc
#     - precise:kpi:coverage
#     - precise:kpi:unittest
#     - precise:kpi:doc
#   script:
#     - echo precise:publish

# # ---------------------------------------------------------------------------- #

