image: ubuntu:16.04

stages:
  - builder
  - compile
  - kpi
  - publish

xenial:builder:
  stage: builder
  script:
    - echo builder:xenial

xenial:compile:release:
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  image: xtdcpp/builder/xenial
  dependencies:
  - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:compile:debug:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:kpi:doc:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} doc
    - make -C ${CI_BUILDDIR} doc-coverage -j

xenial:kpi:unittest:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} check -j
    - make -C ${CI_BUILDDIR} memcheck -j

xenial:kpi:coverage:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cov -j

xenial:kpi:cloc:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cloc -j

xenial:kpi:cppcheck:
  image: xtdcpp/builder/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cppcheck -j

xenial:publish:
  image: xtdcpp/builder/xenial
  stage: publish
  dependencies:
    - xenial:kpi:cppcheck
    - xenial:kpi:cloc
    - xenial:kpi:coverage
    - xenial:kpi:unittest
    - xenial:kpi:doc
  script:
    - echo xenial:publish
