image: ubuntu:16.04

stages:
  - builder
  - compile
  - kpi
  - publish

builder:xenial:
  stage: builder
  script:
    - echo builder:xenial

builder:trusty:
  stage: builder
  script:
    - echo builder:trusty

xenial:compile:release:
  dependencies:
  - xenial:builder
  stage: compile
  script:
    - echo xenial:compile:release

xenial:compile:debug:
  dependencies:
  - xenial:builder
  stage: compile
  script:
    - echo xenial:compile:release

xenial:kpi:doc:
  dependencies:
  - xenial:compile:debug
  stage: kpi
  script:
    - echo xenial:kpi:doc
    - echo xenial:kpi:doc-coverage

xenial:kpi:unittest:
  dependencies:
  - xenial:compile:release
  stage: kpi
  script:
    - echo xenial:kpi:unittest
    - echo xenial:kpi:memcheck

xenial:kpi:coverage:
  dependencies:
  - xenial:compile:debug
  stage: kpi
  script:
    - echo xenial:kpi:coverage

xenial:kpi:cloc:
  dependencies:
  - xenial:compile:debug
  stage: kpi
  script:
    - echo xenial:kpi:cloc

xenial:kpi:cppcheck:
  dependencies:
  - xenial:compile:debug
  stage: kpi
  script:
    - echo xenial:kpi:cppcheck

xenial:publish:
  stage: publish
  dependencies:
    - xenial:kpi:cppcheck
    - xenial:kpi:cloc
    - xenial:kpi:coverage
    - xenial:kpi:unittest
    - xenial:kpi:doc
  script:
    - echo xenial:publish
