image: ubuntu:16.04

stages:
  - builder
  - compile
  - kpi
  - publish

# ---------------------------------------------------------------------------- #

xenial:builder:
  image: docker:latest
  variables:
    CI_LSB_RELEASE: xenial
  stage: builder
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/builder

trusty:builder:
  image: docker:latest
  variables:
    CI_LSB_RELEASE: trusty
  stage: builder
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/builder

# ---------------------------------------------------------------------------- #

xenial:compile:release:
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  dependencies:
  - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:compile:debug:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

xenial:kpi:doc:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} doc
    - make -C ${CI_BUILDDIR} doc-coverage -j

xenial:kpi:unittest:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: release
  dependencies:
    - xenial:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} check -j
    - make -C ${CI_BUILDDIR} memcheck -j

xenial:kpi:coverage:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cov -j

xenial:kpi:cloc:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cloc -j

xenial:kpi:cppcheck:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  variables:
    CI_LSB_RELEASE: xenial
    CI_BUILD_TYPE: debug
  dependencies:
    - xenial:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cppcheck -j

xenial:publish:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/xenial
  stage: publish
  dependencies:
    - xenial:kpi:cppcheck
    - xenial:kpi:cloc
    - xenial:kpi:coverage
    - xenial:kpi:unittest
    - xenial:kpi:doc
  script:
    - echo xenial:publish

# ---------------------------------------------------------------------------- #

trusty:compile:release:
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  dependencies:
  - trusty:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

trusty:compile:debug:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:builder
  stage: compile
  script:
    - sed -i 's%git@github.com:%https://github.com/%g' ${CI_PROJECT_DIR}/.gitmodules ${CI_PROJECT_DIR}/.git/config
    - cd ${CI_PROJECT_DIR} && git submodule init
    - cd ${CI_PROJECT_DIR} && git submodule update
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - ${CI_PROJECT_DIR}/gitlab-ci/bootstrap
    - make -C ${CI_BUILDDIR} all -j

trusty:kpi:doc:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  dependencies:
    - trusty:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} doc
    - make -C ${CI_BUILDDIR} doc-coverage -j

trusty:kpi:unittest:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: release
  dependencies:
    - trusty:compile:release
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} check -j
    - make -C ${CI_BUILDDIR} memcheck -j

trusty:kpi:coverage:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cov -j

trusty:kpi:cloc:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cloc -j

trusty:kpi:cppcheck:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  variables:
    CI_LSB_RELEASE: trusty
    CI_BUILD_TYPE: debug
  dependencies:
    - trusty:compile:debug
  stage: kpi
  script:
    - . ${CI_PROJECT_DIR}/gitlab-ci/env
    - make -C ${CI_BUILDDIR} cppcheck -j

trusty:publish:
  image: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/trusty
  stage: publish
  dependencies:
    - trusty:kpi:cppcheck
    - trusty:kpi:cloc
    - trusty:kpi:coverage
    - trusty:kpi:unittest
    - trusty:kpi:doc
  script:
    - echo trusty:publish
