sudo: required
services:
    - docker

env:
  global:
  - ENCRYPTION_LABEL: "cac0dab93c8f"

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - docker pull psycofdj/xtdcpp-xenial:latest

script:
  - mkdir ${TRAVIS_BUILD_DIR}/.release
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:latest bash -c "cd ${TRAVIS_BUILD_DIR}/.release && cmake ${TRAVIS_BUILD_DIR} -DCI=TRUE -DCMAKE_BUILD_TYPE=Debug"
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:latest bash -c "cd ${TRAVIS_BUILD_DIR}/.release && make all -j2"
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:latest bash -c "cd ${TRAVIS_BUILD_DIR}/.release && make reports -j2"
  - ${TRAVIS_BUILD_DIR}/travis-ci/push-doc
