sudo: required
services:
    - docker

env:
  global:
  - ENCRYPTION_LABEL: "cac0dab93c8f"

git:
  # disable the default submodule logic
  submodules: false

before_install:
  # use sed to replace the SSH URL with the public URL, then init and update submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - docker pull psycofdj/xtdcpp-xenial:1.2.0

script:
  - mkdir ${TRAVIS_BUILD_DIR}/.release
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:1.1.1 bash -c "cd ${TRAVIS_BUILD_DIR}/.release && cmake ${TRAVIS_BUILD_DIR} -DCI=TRUE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON"
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:1.1.1 bash -c "cd ${TRAVIS_BUILD_DIR}/.release && make all -j2"
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:1.1.1 bash -c "cd ${TRAVIS_BUILD_DIR}/.release && make reports -j2"
  - docker run -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} psycofdj/xtdcpp-xenial:1.1.1 bash -c "${TRAVIS_BUILD_DIR}/travis-ci/statuses.py --token=${access_token} --build-id=${TRAVIS_BUILD_ID} --commit=${TRAVIS_COMMIT} --branch=${TRAVIS_BRANCH} --build-dir=${TRAVIS_BUILD_DIR}/.release"
  - cd ${TRAVIS_BUILD_DIR}/.release && ${TRAVIS_BUILD_DIR}/travis-ci/push-doc
