set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/modules")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/cppcheck")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/doc")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/doc-coverage")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/cloc")
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/xtdmake/interface")
# include(xtdmake/tracking/module.cmake)
# include(xtdmake/static-shared/module.cmake)
# include(xtdmake/doc/module.cmake)
# include(xtdmake/doc-coverage/module.cmake)
# include(xtdmake/cloc/module.cmake)
# include(xtdmake/cppcheck/module.cmake)
# include(xtdmake/interface/module.cmake)
