#!/bin/bash
set -e
set -x

mkdir -p ${CI_SRCDIR} ${CI_BUILDDIR}
l_dir=$(mktemp -d)
rsync --temp-dir ${l_dir} -tr --delete ${CI_PROJECT_DIR}/ ${CI_SRCDIR}

if [ ! -f ${CI_BUILDDIR}/Makefile ]; then
    cd ${CI_BUILDDIR}/
    if [ "${CI_BUILD_TYPE}" = "debug" ]; then
        cmake -DCI=TRUE -DCMAKE_BUILD_TYPE=Debug ${CI_SRCDIR}
    else
      cmake -DCI=TRUE -DCMAKE_BUILD_TYPE=Release ${CI_SRCDIR}
    fi
fi
