#!/bin/bash

l_dir=docker/builder/${CI_LSB_RELEASE}/
l_file=${l_dir}/Dockerfile
l_hash=$(md5sum ${l_file} | cut -d' ' -f1)
l_image=${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_REF_NAME}/${CI_LSB_RELEASE}
l_tmp=$(mktemp)
docker inspect -f "{{ index .Config.Labels \"ci.gitlab.hash\"}}" ${l_image} > ${l_tmp} 2> /dev/null

l_got=""
if [ $? -eq 0 ]; then
    l_got=$(cat ${l_tmp})
fi

if [ "${l_got}" != "${l_hash}" ]; then
    docker build \
           -t ${l_image} \
           --label ci.gitlab.hash=${l_hash} \
           docker/builder/${CI_LSB_RELEASE}/
fi

rm -f ${l_tmp}
