#!/bin/bash

set -e

# copying debug reports in release reports
for c_dir in $(find ${CI_WORK_DIR}/${CI_LSB_RELEASE}/debug/build/reports  -mindepth 1 -maxdepth 1 -type d); do
  l_name=$(basename ${c_dir})
  rm -rf ${CI_WORK_DIR}/${CI_LSB_RELEASE}/release/build/reports/${l_name}
  cp -r ${CI_WORK_DIR}/${CI_LSB_RELEASE}/debug/build/reports/${l_name} ${CI_WORK_DIR}/${CI_LSB_RELEASE}/release/build/reports/${l_name}
done

# updating release report interface
make -C ${CI_WORK_DIR}/${CI_LSB_RELEASE}/release/build reports-update

# copying reports into branch
rm -rf ${CI_WORK_DIR}/${CI_LSB_RELEASE}/reports
cp -r ${CI_WORK_DIR}/${CI_LSB_RELEASE}/release/build/reports ${CI_WORK_DIR}/${CI_LSB_RELEASE}/reports
